### ISSUE TITLE
feat: create perks API

### ISSUE THREAD

**Issue by tanishdotdev** [bluppco/vincit#21]
Slug: 7baacef09f9f441abcd816b062971b39

Add these fields:

- [ ] Title ( title )
- [ ] Slug ( formula )
- [ ] Description ( rich_text )
- [ ] Is Active ( checkbox )
- [ ] Display on Home ( checkbox )
- [ ] Order ( number )
- [ ] has_order = true 
- [ ] has_md = f 
- [ ] has_images = f

**Comment by devdotmohit** [comment]
Cool.
